name: 🚀 DEPLOYING NRW 's Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('NRW/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: 🔨 Build Project
        working-directory: ./NRW
        run: |
          npm install --legacy-peer-deps
          CI=false npx ng build

      - name: 📂 Deploy in ftp server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.smart-sfax.org
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./NRW/dist/nrw/
          server-dir: /nrw.ieee.tn/
